//! Fan-out emission and its stagger — RFC 6 §2.7.
//!
//! A group message is sealed once per member. `G−1` objects appearing within a
//! short window, all in the same size bucket, is visible as *"someone just
//! sent to about G people"* — and with tight timing, possibly **which** G
//! tags. That undoes a large part of the unlinkability fan-out was paid for.
//!
//! ```text
//! Implementations MUST stagger fan-out emission over a randomised window.
//! W MUST be derived from the observed background arrival rate, NOT a constant.
//! ```
//!
//! # The window
//!
//! RFC 6 §2.7 gives a table rather than a formula. The table is generated by
//! one:
//!
//! ```text
//! W = (G − 1) / (LIFT × background)      hours, objects/hour
//! ```
//!
//! at `LIFT = 0.10` — a ten percent local rate lift. Against the published
//! rows:
//!
//! | network | background | G | table | formula |
//! |---|---|---|---|---|
//! | n=100 | 8.3/h | 10 | 10.8 h | 9 / 0.83 = 10.8 |
//! | n=100 | 8.3/h | 20 | 22.8 h | 19 / 0.83 = 22.9 |
//! | n=100 | 8.3/h | 50 | 58.8 h | 49 / 0.83 = 59.0 |
//! | n=500 | 41.7/h | 20 | 4.6 h | 19 / 4.17 = 4.6 |
//! | n=2000 | 166.7/h | 50 | 2.9 h | 49 / 16.67 = 2.9 |
//!
//! The counterintuitive part is in the RFC and falls out of the formula: a
//! **quieter** network needs a **longer** window, because there is less
//! traffic to hide in.
//!
//! # An unmeasured rate is not an excuse for a constant
//!
//! A node that has just started has observed nothing. It cannot substitute a
//! convenient number — that is the constant the RFC forbids. It assumes the
//! quietest network it has evidence for, which produces the **widest** window.
//! Being slow is a cost to the operator; being fast is a cost to everyone in
//! the group.

use krab_crypto::rng::Rng;

/// The local rate lift the window is sized for — RFC 6 §2.7's ten percent.
pub const LIFT: f64 = 0.10;

/// The background rate assumed before anything has been observed, in objects
/// per hour.
///
/// RFC 6 §2.7's quietest published network (n=100). Not a default window —
/// a default *observation*, and the most conservative one in the RFC, so an
/// unmeasured node staggers more rather than less.
pub const UNOBSERVED_RATE: f64 = 8.3;

/// Seconds to spread `members` emissions over, given a background rate.
///
/// Returns whole seconds because that is what a scheduler can act on.
pub fn window_seconds(members: usize, background_per_hour: f64) -> u64 {
    let copies = members.saturating_sub(1) as f64;
    if copies <= 0.0 {
        return 0;
    }
    let rate = if background_per_hour.is_finite() && background_per_hour > 0.0 {
        background_per_hour
    } else {
        UNOBSERVED_RATE
    };
    let hours = copies / (LIFT * rate);
    // A window longer than the acceptance window would strand the message:
    // RFC 1 §6.2 gives an object `MAX_TTL` to arrive, and an emission that
    // has not happened yet cannot arrive at all.
    let cap = (krab_core::tag::MAX_TTL_DAYS as f64) * 24.0 * 3600.0 / 2.0;
    ((hours * 3600.0).min(cap)) as u64
}

/// When each copy is released, as offsets in seconds from now.
///
/// **Uniform and independent, not evenly spaced.** Even spacing over a window
/// is a signature of its own: `G−1` objects at a fixed interval identifies the
/// sender's fan-out as surely as a burst does, and lets an observer read `G`
/// off the interval.
///
/// The first copy is *not* released immediately for the same reason — an
/// object at t=0 followed by a spread tail marks the start of the fan-out.
pub fn offsets(members: usize, background_per_hour: f64, rng: &mut impl Rng) -> Vec<u64> {
    let copies = members.saturating_sub(1);
    let w = window_seconds(members, background_per_hour);
    if copies == 0 || w == 0 {
        return vec![0; copies];
    }
    let mut out = Vec::with_capacity(copies);
    for _ in 0..copies {
        let mut b = [0u8; 8];
        rng.fill(&mut b);
        out.push(u64::from_le_bytes(b) % (w + 1));
    }
    out
}

/// A sealed copy waiting for its release time.
pub struct Pending {
    /// Seconds since the Unix epoch at which this copy enters the corpus.
    pub release_at_s: u64,
    /// The object identifier.
    pub id: krab_core::object::ObjectId,
    /// The object's canonical bytes.
    pub bytes: Vec<u8>,
}

impl core::fmt::Debug for Pending {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        // Never the bytes: this is a sealed message awaiting emission, and a
        // debug line is a place plaintext-adjacent material escapes to.
        write!(
            f,
            "Pending(release_at_s: {}, {} bytes)",
            self.release_at_s,
            self.bytes.len()
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use krab_crypto::rng::NotRandom;

    /// **The formula reproduces RFC 6 §2.7's table.** If this fails, either
    /// the table or the derivation is wrong, and the window an implementation
    /// actually uses is not the one the RFC published.
    #[test]
    fn the_window_matches_the_published_table() {
        // The table's background rates are themselves rounded to one decimal:
        // "8.3/h" is 200 objects a day over 24 hours, which is 8.333. Testing
        // against the printed rate would be testing the rounding. These are
        // the unrounded rates, and every published figure then matches to the
        // decimal it was printed at.
        let rates = [
            (200.0 / 24.0, "n=100"),
            (1_000.0 / 24.0, "n=500"),
            (4_000.0 / 24.0, "n=2000"),
        ];
        let table = [[10.8, 22.8, 58.8], [2.2, 4.6, 11.8], [0.5, 1.1, 2.9]];
        for (row, (rate, name)) in rates.iter().enumerate() {
            for (col, g) in [10usize, 20, 50].iter().enumerate() {
                let hours = window_seconds(*g, *rate) as f64 / 3600.0;
                let rounded = (hours * 10.0).round() / 10.0;
                assert_eq!(
                    rounded, table[row][col],
                    "{name}, G={g}: the RFC publishes {} h, this gives {hours:.3} h",
                    table[row][col]
                );
            }
        }
    }

    /// **A quieter network needs a longer window.** Counterintuitive, in the
    /// RFC, and the property most likely to be "fixed" by someone who thinks
    /// it is backwards.
    #[test]
    fn a_quieter_network_staggers_for_longer() {
        assert!(
            window_seconds(20, 8.3) > window_seconds(20, 166.7),
            "less traffic must mean a wider window — there is less to hide in"
        );
    }

    /// An unobserved rate produces the **widest** window the RFC publishes,
    /// not a convenient constant.
    #[test]
    fn an_unmeasured_rate_is_conservative() {
        let unmeasured = window_seconds(20, 0.0);
        assert_eq!(unmeasured, window_seconds(20, UNOBSERVED_RATE));
        assert!(unmeasured >= window_seconds(20, 41.7));
        // And nothing pathological from nonsense input.
        assert_eq!(window_seconds(20, f64::NAN), unmeasured);
        assert_eq!(window_seconds(20, -5.0), unmeasured);
    }

    /// A window longer than the acceptance window would strand the message:
    /// an emission that has not happened cannot arrive.
    #[test]
    fn the_window_is_capped_below_the_acceptance_window() {
        let max = window_seconds(usize::MAX, 0.000_001);
        let ttl = krab_core::tag::MAX_TTL_DAYS as u64 * 24 * 3600;
        assert!(max < ttl, "a copy would be released after it could arrive");
    }

    /// One member is oneself; there is nothing to fan out to.
    #[test]
    fn a_group_of_one_emits_nothing() {
        assert_eq!(window_seconds(1, 8.3), 0);
        assert!(offsets(1, 8.3, &mut NotRandom::seeded(1)).is_empty());
    }

    /// **Offsets are independent, not evenly spaced.** Even spacing is a
    /// signature: `G−1` objects at a fixed interval identifies the fan-out as
    /// surely as a burst, and lets an observer read `G` off the interval.
    #[test]
    fn offsets_are_spread_and_not_regular() {
        let mut rng = NotRandom::seeded(7);
        let o = offsets(20, 41.7, &mut rng);
        assert_eq!(o.len(), 19);

        let w = window_seconds(20, 41.7);
        assert!(
            o.iter().all(|&x| x <= w),
            "an offset fell outside the window"
        );

        // Not all identical, and not a constant interval.
        let mut sorted = o.clone();
        sorted.sort();
        let gaps: Vec<u64> = sorted.windows(2).map(|p| p[1] - p[0]).collect();
        assert!(
            gaps.iter().collect::<std::collections::HashSet<_>>().len() > 1,
            "the offsets are evenly spaced, which is its own signature: {o:?}"
        );

        // And they use the window rather than clustering at its start.
        assert!(
            *sorted.last().unwrap() > w / 2,
            "nothing was scheduled in the second half of the window: {sorted:?}"
        );
    }

    /// Nothing is released at t=0: an object now, followed by a spread tail,
    /// marks the start of the fan-out.
    #[test]
    fn offsets_do_not_all_start_immediately() {
        let mut rng = NotRandom::seeded(3);
        let o = offsets(10, 8.3, &mut rng);
        assert!(
            o.iter().filter(|&&x| x == 0).count() < o.len(),
            "every copy was released immediately: {o:?}"
        );
    }

    /// Drawn from the supplied generator, never ambient — the rule the whole
    /// codebase is built on.
    #[test]
    fn offsets_come_from_the_supplied_generator() {
        let a = offsets(10, 41.7, &mut NotRandom::seeded(4));
        let b = offsets(10, 41.7, &mut NotRandom::seeded(4));
        assert_eq!(a, b);
        assert_ne!(a, offsets(10, 41.7, &mut NotRandom::seeded(5)));
    }
}
