//! RFC 1 §12 test vectors.
//!
//! > "RFC 1 MUST NOT reach Final without machine-checkable vectors covering, at
//! > minimum: canonical encoding of each class; identifier derivation; pairwise
//! > and inbox tag derivation across an epoch boundary; AAD construction;
//! > `mode_auth` and `mode_base` seal/open; each padding bucket boundary; and
//! > every rejection case in §11.
//! >
//! > Two independent implementations MUST agree on every vector before the
//! > status changes. **For a format that cannot be revised, vectors are the
//! > specification; the prose is commentary.**"
//!
//! # What this module is, and what it is not
//!
//! It emits `Documentation/vectors/rfc-1.txt` — a flat, line-oriented file
//! another implementation can read without a CBOR parser or a JSON library, in
//! any language. That matters because the audience is *the second
//! implementation*, which by definition does not share this one's code.
//!
//! The committed file is checked on every test run. If the implementation
//! drifts, the test fails; if the vectors are regenerated carelessly, the diff
//! is visible in review. Neither alone is sufficient and together they are the
//! protection.
//!
//! # The circularity, and how far it is reduced
//!
//! A vector file generated by the implementation it checks proves only
//! self-consistency. An output on its own — `tag.pairwise.20670 d39db230…` —
//! is checkable *only* by rebuilding whatever produced it, which is what a
//! second implementation is for.
//!
//! So every derived value is emitted next to the inputs it came from: the
//! literal `info` bytes for each tag, the agreed secret and both private keys,
//! the full canonical preimage of every object identifier, the header's fields
//! beside its encoding. The file states which hash each derivation uses, since
//! §6.2 names none. A reader holding RFC 1 and a hash utility can confirm the
//! constructions without running any of this.
//!
//! `Documentation/vectors/check.py` does exactly that, in about three hundred
//! lines of standard-library Python: it anchors its own X25519 against
//! RFC 7748 §5.2 and §6.1 and its own HKDF-Expand against RFC 5869 §A.1, then
//! recomputes every published derivation. It shares no code with this
//! implementation.
//!
//! # What that is worth, and what it is not
//!
//! It catches the errors that do not need a second *reader* to find — a
//! swapped concatenation, a wrong endianness, a label off by a byte, an
//! Extract step that should not be there. It found one on its first run: the
//! vector file's own comment said the routing header's expiry was big-endian,
//! and it is little-endian.
//!
//! It does not catch a **misreading of RFC 1**, because it was written by the
//! same author from the same reading. If §6.2 has been misunderstood here, it
//! is misunderstood there too, and the two agreeing would look like evidence
//! while being none.
//!
//! **RFC 1 cannot reach Final on this file alone.** §12 requires two
//! independent implementations to agree, and there is one. Nothing in this
//! module changes that; what it changes is how much of the disagreement a
//! second implementer would be able to localise when they arrive — a failing
//! line now comes with its inputs, rather than with a number and a shrug.

use crate::compose::{aad_for, body_size_for, bucket_for, seal_to, Recipient, SUITE_V1};
use krab_core::object::{
    canonical_bytes, decode_envelope, Envelope, RoutingHeader, Tag, BUCKETS, ROUTING_HEADER_LEN,
};
use krab_core::tag::Epoch;
use krab_crypto::dh::SecretKey;
use krab_crypto::rng::NotRandom;
use krab_crypto::seal::{info_for, ENC_LEN};
use krab_store::index::{Reject, Store};

/// Where the committed file lives, relative to the workspace root.
pub const VECTOR_FILE: &str = "Documentation/vectors/rfc-1.txt";

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

fn sk(seed: u64) -> SecretKey {
    SecretKey::generate(&mut NotRandom::seeded(seed))
}

/// Produce every vector RFC 1 §12 enumerates.
pub fn generate() -> String {
    let mut out = String::new();
    out.push_str(
        "# RFC 1 §12 test vectors.\n\
         #\n\
         # Flat and line-oriented on purpose: the audience is a second\n\
         # implementation, which needs no CBOR parser to read this.\n\
         # Format: <name> <space> <hex or decimal>\n\
         #\n\
         # Generated by apps/krab-tui/src/vectors.rs and checked on every test\n\
         # run. RFC 1 §12 requires two independent implementations to agree\n\
         # before RFC 1 reaches Final; there is currently one.\n\
         #\n\
         # ---------------------------------------------------------------\n\
         # CHECKABLE BY INSPECTION\n\
         # ---------------------------------------------------------------\n\
         #\n\
         # Every derived value is printed together with the inputs it was\n\
         # derived from, so a reader holding RFC 1 can confirm the derivation\n\
         # with a hash utility and no Krab code at all. That is the point: an\n\
         # output on its own is only checkable by rebuilding the thing that\n\
         # produced it, which is what a second implementation is for and what\n\
         # this file cannot substitute for.\n\
         #\n\
         # What it *can* catch is the class of error that does not need a\n\
         # second reader to find: a swapped concatenation order, the wrong\n\
         # endianness on an epoch, a label off by a byte, an output length\n\
         # taken from the wrong line of the spec. Those are visible here.\n\
         #\n\
         # Each block says what agreement with it is worth:\n\
         #\n\
         #   anchor: external    values computed outside this codebase, with a\n\
         #                       different implementation of the primitive.\n\
         #                       Agreement is evidence of correctness.\n\
         #   anchor: derivable   recomputable by hand from the inputs printed\n\
         #                       above them, using only the named standard\n\
         #                       primitives. Agreement is evidence the\n\
         #                       construction is what the RFC describes.\n\
         #   anchor: drift       self-consistency only. Agreement means this\n\
         #                       implementation has not changed. It is NOT\n\
         #                       evidence that it is right.\n\
         #\n\
         # ---------------------------------------------------------------\n\
         # PRIMITIVES, NAMED\n\
         # ---------------------------------------------------------------\n\
         #\n\
         # RFC 1 §6.2 writes \"HKDF-Expand\" and never names a hash, which\n\
         # taken alone is not implementable interoperably. §6.1 pins the\n\
         # suite's KDF, and this file follows that reading. The wrong\n\
         # inference is the natural one — every other digest in Krab is\n\
         # BLAKE3 — so it is stated here rather than left to be guessed:\n\
         #\n\
         #   object identifiers (§4)   BLAKE3-256\n\
         #   tag derivation (§6.2)     HKDF-SHA256, Expand ONLY, no Extract\n\
         #   agreement                 X25519 (RFC 7748), static-static\n\
         #   AEAD (§6.1)               ChaCha20-Poly1305\n\
         #\n\
         # The absent Extract is deliberate and is RFC 1 §6.2 as frozen: the\n\
         # PRK fed to Expand is a raw X25519 output, or for inbox mode a raw\n\
         # public key. See CRYPTO-REVIEW.md §3. An implementation that adds\n\
         # Extract produces different tags for every object and shares mail\n\
         # with nobody, silently.\n\n",
    );

    // ---- §8.1 padding bucket boundaries ----
    out.push_str("## bucket boundaries (§8.1)\n");
    out.push_str(
        "# anchor: derivable — arithmetic on the published ladder.\n\
         # bucket.for.N is the smallest bucket admitting N bytes INCLUDING the\n\
         # 16-byte routing header; `none` means N exceeds the largest bucket.\n",
    );
    for (i, size) in BUCKETS.iter().enumerate() {
        out.push_str(&format!("bucket.{i}.bytes {size}\n"));
        out.push_str(&format!(
            "bucket.for.{size} {}\n",
            bucket_for(*size as usize).unwrap()
        ));
        out.push_str(&format!(
            "bucket.for.{} {}\n",
            size + 1,
            bucket_for(*size as usize + 1)
                .map(|b| b.to_string())
                .unwrap_or("none".into())
        ));
    }
    out.push('\n');

    // ---- §4 canonical encoding and identifier derivation, per class ----
    out.push_str("## canonical encoding and identifiers (§4)\n");
    out.push_str(&format!(
        "# anchor: derivable — id = BLAKE3-256(domain.object ‖ object.bytes).\n\
         # The whole preimage is printed, so no Krab code is needed to check it.\n\
         #\n\
         # The header is 16 bytes: version(1), class(1), size_bucket(1),\n\
         # flags(1), expiry_min(4) as u32 LITTLE-endian, tag(8). The four\n\
         # single bytes have no byte order; the only multi-byte field is the\n\
         # expiry, and it is little-endian — same as the epoch inside a tag's\n\
         # info string, which is the one consistency worth stating out loud.\n\
         #\n\
         # 29766240 is 0x01C63260, so bytes 4..8 read 6032c601. An earlier\n\
         # revision of this comment said big-endian; the checker in this\n\
         # directory disagreed with it, which is the entire point of printing\n\
         # the field values next to the encoding.\n\
         # The object is header ‖ body ‖ zero padding to the bucket size, and\n\
         # the identifier covers the padding — which is why RFC 1 §8.1 fixes\n\
         # padding at zero. `id_with_dirty_padding` is the same object with its\n\
         # final byte set to 1, and is a different identifier.\n\
         domain.object.hex {}\n\
         domain.object.ascii {}\n",
        hex(krab_crypto::hash::DOMAIN_OBJECT),
        core::str::from_utf8(krab_crypto::hash::DOMAIN_OBJECT).unwrap(),
    ));
    for class in 0u8..=1 {
        let h = RoutingHeader {
            version: 1,
            class,
            size_bucket: 0,
            flags: 0,
            expiry_min: 29_766_240,
            tag: Tag([0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88]),
        };
        out.push_str(&format!(
            "header.class{class}.encoded {}\n",
            hex(&h.write())
        ));
        // The header's fields, so a reader can see which byte is which rather
        // than having to trust the field order above.
        out.push_str(&format!("header.class{class}.version 1\n"));
        out.push_str(&format!("header.class{class}.class {class}\n"));
        out.push_str(&format!("header.class{class}.size_bucket 0\n"));
        out.push_str(&format!("header.class{class}.flags 0\n"));
        out.push_str(&format!("header.class{class}.expiry_min 29766240\n"));
        out.push_str(&format!(
            "header.class{class}.tag {}\n",
            hex(&[0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88])
        ));

        let body = [0xABu8; 40];
        let obj = canonical_bytes(&h, &body).unwrap();
        out.push_str(&format!("object.class{class}.body {}\n", hex(&body)));
        out.push_str(&format!("object.class{class}.len {}\n", obj.len()));
        // **The full preimage.** Without it `object.id` is a number a reader
        // can only reproduce by running this implementation, which is the
        // circularity the file exists to reduce.
        out.push_str(&format!("object.class{class}.bytes {}\n", hex(&obj)));
        out.push_str(&format!(
            "object.class{class}.id {}\n",
            hex(&krab_crypto::object_id(&obj).0)
        ));
        // The identifier covers the padding: one flipped pad byte, one new id.
        let mut padded = obj.clone();
        *padded.last_mut().unwrap() = 1;
        out.push_str(&format!(
            "object.class{class}.bytes_with_dirty_padding {}\n",
            hex(&padded)
        ));
        out.push_str(&format!(
            "object.class{class}.id_with_dirty_padding {}\n",
            hex(&krab_crypto::object_id(&padded).0)
        ));
    }
    out.push('\n');

    // ---- §6.2 tag derivation across an epoch boundary ----
    //
    // A fixed PRK rather than a DH output, so the vector does not depend on
    // any implementation's clamping. These values are pinned independently in
    // `krab_crypto::kdf` against a separate HMAC implementation.
    // The construction itself, from a fixed PRK. **These are the anchored
    // ones**: a second implementation can check them with nothing but HMAC-
    // SHA256, without reproducing X25519's clamping, and the values here were
    // computed outside this codebase before being committed.
    out.push_str("## HKDF-Expand construction, fixed PRK (§6.2)\n");
    out.push_str(&format!(
        "# anchor: external — these six outputs were computed outside this\n\
         # codebase, with a separate HMAC implementation, before being\n\
         # committed. A second implementation can check them with nothing but\n\
         # HMAC-SHA256: no X25519, no clamping, no shared assumptions.\n\
         #\n\
         #   tag = HKDF-Expand(prk, info, L)\n\
         #   info = label ‖ u32_le(epoch)\n\
         #   L    = 8\n\
         #\n\
         # NO Extract step. The PRK is used as the HMAC key directly.\n\
         # The epoch is LITTLE-endian: RFC 1 §6.2 writes u32(epoch) and RFC 2\n\
         # §4.1 writes u32_le(epoch); the explicit one governs. Epoch 20670 is\n\
         # 0x50BE, so the info tail reads be500000 and not 000050be — which is\n\
         # the one byte-order error this file exists to make visible.\n\
         #\n\
         # The info bytes are printed in full below. Read them against §6.2 and\n\
         # the concatenation order is checkable by eye.\n\
         kdf.hash SHA-256\n\
         kdf.L 8\n\
         kdf.extract none\n\
         label.tag.hex {}\n\
         label.tag.ascii {}\n\
         label.inbox.hex {}\n\
         label.inbox.ascii {}\n\
         kdf.prk {}\n",
        hex(krab_core::tag::LABEL_TAG),
        core::str::from_utf8(krab_core::tag::LABEL_TAG).unwrap(),
        hex(krab_core::tag::LABEL_INBOX),
        core::str::from_utf8(krab_core::tag::LABEL_INBOX).unwrap(),
        hex(&[0x42u8; 32]),
    ));
    for epoch in [20_670u32, 20_671, 20_672] {
        for (name, label) in [
            ("pairwise", krab_core::tag::LABEL_TAG),
            ("inbox", krab_core::tag::LABEL_INBOX),
        ] {
            // The exact `info` argument, so the reader checks a construction
            // rather than trusting a description of one.
            let mut info = label.to_vec();
            info.extend_from_slice(&Epoch(epoch).to_le_bytes());
            out.push_str(&format!("kdf.info.{name}.{epoch} {}\n", hex(&info)));
            out.push_str(&format!(
                "kdf.{name}.{epoch} {}\n",
                hex(
                    &krab_crypto::kdf::expand_tag_for_vectors(&[0x42u8; 32], label, Epoch(epoch)).0
                )
            ));
        }
    }
    out.push('\n');

    out.push_str("## tag derivation across an epoch boundary (§6.2)\n");
    let a = sk(1);
    let b = sk(2);
    let shared = krab_crypto::agree(&a, &b.public()).unwrap();
    out.push_str(
        "# anchor: derivable — every input is printed, including both private\n\
         # keys and the agreed secret, so this needs no Krab code to check:\n\
         #\n\
         #   kx.shared        = X25519(kx.a.secret, kx.b.public)\n\
         #                    = X25519(kx.b.secret, kx.a.public)   (symmetric)\n\
         #   tag.pairwise.E   = HKDF-Expand(kx.shared,  label.tag   ‖ u32_le(E), 8)\n\
         #   tag.inbox.E      = HKDF-Expand(kx.b.public, label.inbox ‖ u32_le(E), 8)\n\
         #\n\
         # Note what the second line says: the inbox PRK is the recipient's\n\
         # PUBLIC KEY, used verbatim as an HMAC key. That is RFC 1 §6.2 as\n\
         # frozen, and it is why anyone holding the public key can compute the\n\
         # tag — which is what makes first contact possible and what makes\n\
         # messages to an inbox tag linkable within an epoch (RFC 2 §4.2).\n\
         #\n\
         # The private keys are printed because these are test vectors and\n\
         # publishing them is what makes the block checkable. They are\n\
         # generated from a counter and protect nothing.\n\
         #\n\
         # Once kx.shared is confirmed against RFC 7748, the two tag lines\n\
         # reduce to the fixed-PRK block above, which is externally anchored.\n",
    );
    out.push_str(&format!("kx.a.secret {}\n", hex(&a.to_bytes())));
    out.push_str(&format!("kx.a.public {}\n", hex(&a.public().0)));
    out.push_str(&format!("kx.b.secret {}\n", hex(&b.to_bytes())));
    out.push_str(&format!("kx.b.public {}\n", hex(&b.public().0)));
    out.push_str(&format!("kx.shared {}\n", hex(shared.as_bytes())));
    out.push_str(&format!(
        "kx.inbox_prk_is {}\n",
        "kx.b.public — the recipient's public key, used as the PRK"
    ));
    for epoch in [20_670u32, 20_671, 20_672] {
        let e = Epoch(epoch);
        out.push_str(&format!(
            "tag.pairwise.{epoch} {}\n",
            hex(&krab_crypto::pairwise_tag(&shared, e).0)
        ));
        out.push_str(&format!(
            "tag.inbox.{epoch} {}\n",
            hex(&krab_crypto::inbox_tag(&b.public(), e).0)
        ));
    }
    out.push('\n');

    // ---- §6.1 AAD construction ----
    out.push_str("## AAD construction (§6.1)\n");
    let h = RoutingHeader {
        version: 1,
        class: 0,
        size_bucket: 1,
        flags: 0,
        expiry_min: 29_766_240,
        tag: Tag([9; 8]),
    };
    let enc = [0x5Au8; ENC_LEN];
    let env = Envelope {
        epoch: 20_671,
        tag_mode: 0,
        suite: SUITE_V1,
        enc: &enc,
        ciphertext: &[0xCC; 16],
    };
    out.push_str(
        "# anchor: derivable — the inputs are printed, so the concatenation and\n\
         # the CBOR map are both checkable:\n\
         #\n\
         #   aad.prefix = deterministic CBOR map, keys ascending, definite\n\
         #                lengths:  {0: epoch, 1: tag_mode, 2: suite, 4: enc}\n\
         #   aad.full   = aad.header ‖ aad.prefix\n\
         #\n\
         # **Key 5 (the ciphertext) is omitted, and key 3 (admission) is absent\n\
         # entirely** — RFC 1 §4.2. A map with either present is a different\n\
         # AAD and every open fails.\n\
         #\n\
         # Key 4 is *included*, so the AAD cannot be built before the KEM has\n\
         # run. That is what makes §6.1's claim true that the AAD binds epoch\n\
         # and suite as well as expiry, tag and class — the header alone binds\n\
         # only the last three.\n\
         #\n\
         # info.classN is the HPKE info string: \"krab/v1/\" ‖ one byte of\n\
         # class. Not part of the AAD; printed here because §6.1 fixes it and\n\
         # a wrong one fails to open with no other symptom.\n",
    );
    out.push_str(&format!("aad.header {}\n", hex(&h.write())));
    out.push_str("aad.env.epoch 20671\n");
    out.push_str("aad.env.tag_mode 0\n");
    out.push_str(&format!("aad.env.suite {SUITE_V1}\n"));
    out.push_str(&format!("aad.env.enc {}\n", hex(&enc)));
    out.push_str("aad.env.ciphertext_is_omitted 1\n");
    out.push_str("aad.env.admission_is_absent 1\n");
    out.push_str(&format!("aad.prefix {}\n", hex(&env.aad())));
    out.push_str(&format!("aad.full {}\n", hex(&aad_for(&h, &env))));
    out.push_str(&format!(
        "info.prefix.hex {}\n",
        hex(krab_crypto::seal::INFO_PREFIX)
    ));
    out.push_str(&format!(
        "info.prefix.ascii {}\n",
        core::str::from_utf8(krab_crypto::seal::INFO_PREFIX).unwrap()
    ));
    out.push_str(&format!("info.class0 {}\n", hex(&info_for(0))));
    out.push_str(&format!("info.class1 {}\n", hex(&info_for(1))));
    out.push('\n');

    // ---- §6 seal/open, both modes ----
    //
    // HPKE is randomised, so a ciphertext is not a fixed vector. What is
    // pinned is the *shape*: sizes, and that a round trip through the wire
    // form recovers the plaintext.
    out.push_str("## seal and open (§6)\n");
    out.push_str(
        "# anchor: drift — HPKE is randomised, so a ciphertext is not a fixed\n\
         # value and cannot be. What is pinned is the SHAPE: the lengths, the\n\
         # mode, the suite, and that a round trip through the wire form\n\
         # recovers the plaintext.\n\
         #\n\
         # A second implementation checks these by producing its own sealed\n\
         # object and comparing the numbers, not by reproducing these bytes.\n\
         # mode_auth is used for a known correspondent; mode_base for first\n\
         # contact, where the recipient does not yet hold the sender's static\n\
         # key and so cannot decapsulate in auth mode (RFC 2 §4.2).\n",
    );
    for (name, first_contact) in [("mode_auth", false), ("mode_base", true)] {
        let plaintext = b"vector plaintext";
        let epoch = Epoch(20_671);
        let tag = if first_contact {
            krab_crypto::inbox_tag(&b.public(), epoch)
        } else {
            krab_crypto::pairwise_tag(&shared, epoch)
        };
        let recipient = if first_contact {
            Recipient::FirstContact {
                correspondence: &b.public(),
                tag,
            }
        } else {
            Recipient::Known {
                correspondence: &b.public(),
                tag,
                chunk: None,
            }
        };
        let composed = seal_to(
            &a,
            &recipient,
            epoch,
            0,
            29_766_240,
            plaintext,
            &mut NotRandom::seeded(7),
        )
        .unwrap();
        let (env, _) = decode_envelope(&composed.bytes[ROUTING_HEADER_LEN..]).unwrap();
        out.push_str(&format!("{name}.object.len {}\n", composed.bytes.len()));
        out.push_str(&format!("{name}.bucket {}\n", composed.bucket));
        out.push_str(&format!("{name}.tag_mode {}\n", env.tag_mode));
        out.push_str(&format!("{name}.suite {}\n", env.suite));
        out.push_str(&format!("{name}.enc.len {}\n", env.enc.len()));
        out.push_str(&format!("{name}.ciphertext.len {}\n", env.ciphertext.len()));
        out.push_str(&format!("{name}.plaintext.len {}\n", plaintext.len()));
        out.push_str(&format!(
            "{name}.body_size_for {}\n",
            body_size_for(plaintext.len())
        ));
    }
    out.push('\n');

    // ---- §11 rejection cases ----
    out.push_str("## rejection cases (§11)\n");
    out.push_str(
        "# anchor: drift — each line names the refusal an implementation must\n\
         # produce for that input. The NAMES are the checkable part: two\n\
         # implementations agreeing that a case is rejected, but for different\n\
         # reasons, have not agreed about §11.\n",
    );
    for (name, reject) in rejections() {
        out.push_str(&format!("reject.{name} {reject}\n"));
    }
    out
}

/// Every §11 rejection, exercised.
fn rejections() -> Vec<(&'static str, &'static str)> {
    let name_of = |r: Result<(), Reject>| -> &'static str {
        match r {
            Ok(()) => "accepted",
            Err(Reject::Expired) => "Expired",
            Err(Reject::TooFarFuture) => "TooFarFuture",
            Err(Reject::Duplicate) => "Duplicate",
            Err(Reject::Tombstoned) => "Tombstoned",
            Err(Reject::BelowWatermark) => "BelowWatermark",
            Err(Reject::Malformed) => "Malformed",
            Err(Reject::BadPadding) => "BadPadding",
            Err(Reject::IdMismatch) => "IdMismatch",
            Err(Reject::Unrecognised) => "Unrecognised",
            // No catch-all: a new `Reject` variant should fail to compile here
            // rather than silently render as "other" in a specification file.
        }
    };
    const NOW: u32 = 29_766_000;
    let object = |expiry: u32| {
        let h = RoutingHeader {
            version: 1,
            class: 0,
            size_bucket: 0,
            flags: 0,
            expiry_min: expiry,
            tag: Tag([7; 8]),
        };
        let b = canonical_bytes(&h, &[7u8; 40]).unwrap();
        (krab_crypto::object_id(&b), b)
    };

    let mut out = Vec::new();

    // I5 — the identifier must name the content.
    let mut s = Store::new();
    let (_, bytes) = object(NOW + 40_000);
    let (other, _) = object(NOW + 50_000);
    out.push((
        "id_mismatch",
        name_of(s.ingest(other, bytes.clone(), NOW, u32::MAX)),
    ));

    // I1 — length must equal the declared bucket.
    let mut short = bytes.clone();
    short.truncate(short.len() - 1);
    let id = krab_crypto::object_id(&short);
    out.push(("bad_length", name_of(s.ingest(id, short, NOW, u32::MAX))));

    // I2 — expiry in the past, and beyond MAX_TTL.
    let (id, b) = object(NOW - 1);
    out.push(("expired", name_of(s.ingest(id, b, NOW, u32::MAX))));
    let (id, b) = object(NOW + 100_000);
    out.push(("too_far_future", name_of(s.ingest(id, b, NOW, 1_000))));

    // I6 — duplicate.
    let (id, b) = object(NOW + 40_000);
    let _ = s.ingest(id, b.clone(), NOW, u32::MAX);
    out.push(("duplicate", name_of(s.ingest(id, b, NOW, u32::MAX))));

    // I3 — version and class must be recognised. A v2 object is well-formed
    // and unreadable here; storing it would mean relaying bytes whose meaning
    // this node cannot check.
    let mut junk = bytes.clone();
    junk[0] = 2; // version
    let id = krab_crypto::object_id(&junk);
    out.push(("bad_version", name_of(s.ingest(id, junk, NOW, u32::MAX))));

    let mut junk = bytes.clone();
    junk[1] = 0xFF; // class
    let id = krab_crypto::object_id(&junk);
    out.push(("bad_class", name_of(s.ingest(id, junk, NOW, u32::MAX))));

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn committed() -> Option<String> {
        // Tests run from the crate directory; the file lives at the workspace
        // root.
        std::fs::read_to_string(std::path::Path::new("../..").join(VECTOR_FILE)).ok()
    }

    /// **The drift check.** If the implementation changes, this fails; if the
    /// vectors are regenerated carelessly, the diff is visible in review.
    #[test]
    fn the_implementation_matches_the_committed_vectors() {
        let generated = generate();
        let Some(committed) = committed() else {
            panic!(
                "{VECTOR_FILE} is missing. Regenerate with:\n\n  \
                 cargo test -p krab-tui -- --ignored write_vectors\n"
            );
        };
        if generated != committed {
            let g: Vec<&str> = generated.lines().collect();
            let c: Vec<&str> = committed.lines().collect();
            let first = g
                .iter()
                .zip(c.iter())
                .position(|(a, b)| a != b)
                .map(|i| format!("line {}: {:?} vs committed {:?}", i + 1, g[i], c[i]))
                .unwrap_or_else(|| format!("length {} vs {}", g.len(), c.len()));
            panic!("vectors drifted — {first}");
        }
    }

    /// Regenerate. Ignored by default so it cannot silently paper over drift.
    #[test]
    #[ignore = "writes Documentation/vectors/rfc-1.txt"]
    fn write_vectors() {
        let path = std::path::Path::new("../..").join(VECTOR_FILE);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, generate()).unwrap();
    }

    /// §12's coverage list, checked item by item against the file rather than
    /// assumed. A vector file missing a category is worse than no file, since
    /// it implies coverage it does not have.
    #[test]
    fn every_category_rfc1_names_is_present() {
        let v = generate();
        for (category, marker) in [
            ("canonical encoding of each class", "header.class1.encoded"),
            ("identifier derivation", "object.class0.id "),
            (
                "pairwise tags across an epoch boundary",
                "tag.pairwise.20672",
            ),
            ("inbox tags across an epoch boundary", "tag.inbox.20672"),
            ("AAD construction", "aad.full"),
            ("mode_auth seal/open", "mode_auth.ciphertext.len"),
            ("mode_base seal/open", "mode_base.tag_mode"),
            ("each padding bucket boundary", "bucket.5.bytes"),
            ("§11 rejections", "reject.id_mismatch"),
        ] {
            assert!(
                v.contains(marker),
                "§12 requires {category}; {marker:?} is absent"
            );
        }
    }

    /// Every §11 rejection produces the expected refusal, not an acceptance.
    #[test]
    fn every_rejection_case_actually_rejects() {
        for (name, outcome) in rejections() {
            assert_ne!(outcome, "accepted", "§11 case {name} was accepted");
            assert_ne!(
                outcome, "other",
                "§11 case {name} produced an unnamed reject"
            );
        }
    }

    /// **Where the circularity is broken.** The fixed-PRK vectors were
    /// computed outside this codebase, with a separate HMAC implementation, and
    /// a second implementation can check them using nothing but HMAC-SHA256 —
    /// no X25519, no clamping, no shared assumptions.
    #[test]
    fn the_kdf_vectors_are_independently_anchored() {
        let v = generate();
        // Computed in Python before being committed here.
        for (line, expected) in [
            ("kdf.pairwise.20670", "9df7b6895987ed3c"),
            ("kdf.pairwise.20671", "2daceced91f7148c"),
            ("kdf.pairwise.20672", "77f7856b7dbebdea"),
            ("kdf.inbox.20670", "684f0e4dde844750"),
            ("kdf.inbox.20671", "249743bc3eadc595"),
            ("kdf.inbox.20672", "b4296a826dba95f8"),
        ] {
            assert!(
                v.contains(&format!("{line} {expected}")),
                "{line} does not match the independently computed {expected}"
            );
        }
    }

    /// **The checker in `Documentation/vectors/` agrees with the file.**
    ///
    /// It is not RFC 1 §12's second implementation — same author, same reading
    /// of §6.2 — but it does not share a line of code with this one, it
    /// anchors its own primitives against RFC 7748 and RFC 5869 before using
    /// them, and it recomputes every derivation from the inputs the file
    /// publishes.
    ///
    /// It has already earned its place: its first run disagreed with the
    /// vector file's own comment about the routing header's byte order, and
    /// the comment was the thing that was wrong.
    ///
    /// Skipped where there is no `python3`, because a missing interpreter is
    /// not a failing vector and a test that cannot tell those apart is worse
    /// than no test.
    #[test]
    fn the_independent_checker_agrees() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .ancestors()
            .nth(2)
            .expect("workspace root")
            .to_path_buf();
        let script = root.join("Documentation/vectors/check.py");
        assert!(
            script.exists(),
            "the checker is missing: {}",
            script.display()
        );

        let Ok(out) = std::process::Command::new("python3").arg(&script).output() else {
            eprintln!("no python3; skipping the independent check");
            return;
        };
        assert!(
            out.status.success(),
            "the independent checker rejected the vectors:\n{}\n{}",
            String::from_utf8_lossy(&out.stdout),
            String::from_utf8_lossy(&out.stderr),
        );
    }

    /// **The checker rejects a tampered file.**
    ///
    /// A checker that always passes is worse than none, and one that reads a
    /// key it never checks is the easy way to get one. Each mutation below is
    /// a real error someone could make; each must be caught.
    ///
    /// The first is the whole reason the `info` bytes are published:
    /// `be500000` is 20670 little-endian, and `000050be` is the same number
    /// written the way RFC 1 §6.2's bare `u32(epoch)` invites. Two
    /// implementations differing there share no tags and no mail, and RFC 0 §6
    /// makes that failure silent.
    #[test]
    fn the_checker_rejects_a_tampered_file() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .ancestors()
            .nth(2)
            .expect("workspace root")
            .to_path_buf();
        let script = root.join("Documentation/vectors/check.py");
        let good = std::fs::read_to_string(root.join(VECTOR_FILE)).expect("the vectors");

        if std::process::Command::new("python3")
            .arg("--version")
            .output()
            .is_err()
        {
            eprintln!("no python3; skipping");
            return;
        }

        let mutations: [(&str, &str, &str); 4] = [
            (
                "the epoch written big-endian",
                "kdf.info.pairwise.20670 6b7261622f7461672f7631be500000",
                "kdf.info.pairwise.20670 6b7261622f7461672f7631000050be",
            ),
            (
                "a tag that is not the expansion",
                "tag.inbox.20671 ",
                "tag.inbox.20671 deadbeefdeadbeef #",
            ),
            (
                "an expiry that is not in the header",
                "header.class0.expiry_min 29766240",
                "header.class0.expiry_min 29766241",
            ),
            (
                "a bucket boundary off by one",
                "bucket.for.257 1",
                "bucket.for.257 0",
            ),
        ];

        for (what, from, to) in mutations {
            assert!(good.contains(from), "the anchor moved: {from}");
            let dir = std::env::temp_dir().join(format!("krab-vec-{}", from.len()));
            std::fs::create_dir_all(&dir).ok();
            let path = dir.join("mutated.txt");
            // Replace only the first line beginning with the anchor, so a
            // prefix like `tag.inbox.20671 ` cannot rewrite something else.
            let mutated: String = good
                .lines()
                .map(|l| {
                    if l.starts_with(from) {
                        to.to_string()
                    } else {
                        l.to_string()
                    }
                })
                .collect::<Vec<_>>()
                .join("\n");
            std::fs::write(&path, &mutated).expect("write");

            let out = std::process::Command::new("python3")
                .arg(&script)
                .arg(&path)
                .output()
                .expect("run the checker");
            assert!(
                !out.status.success(),
                "the checker accepted {what}:\n{}",
                String::from_utf8_lossy(&out.stdout),
            );
            std::fs::remove_file(&path).ok();
        }
    }

    /// The DH-derived tags cross an epoch boundary and stay distinct.
    ///
    /// No longer drift-only: the file now publishes both private keys and the
    /// agreed secret, so `check.py` reproduces the X25519 and the expansion
    /// from scratch. What this test still adds is the *property* — three
    /// consecutive epochs give three different tags, which is the whole reason
    /// the epoch is in the info string.
    #[test]
    fn the_tag_vectors_cross_an_epoch_boundary() {
        let v = generate();
        assert!(v.contains("tag.pairwise.20670"));
        assert!(v.contains("tag.pairwise.20671"));
        assert!(v.contains("tag.pairwise.20672"));
        // Epoch boundary: three consecutive epochs, three distinct tags.
        let tags: Vec<&str> = v
            .lines()
            .filter(|l| l.starts_with("tag.pairwise."))
            .map(|l| l.split_whitespace().nth(1).unwrap())
            .collect();
        assert_eq!(tags.len(), 3);
        assert_ne!(tags[0], tags[1]);
        assert_ne!(tags[1], tags[2]);
    }
}
