//! RFC 1 §12 test vectors.
//!
//! > "RFC 1 MUST NOT reach Final without machine-checkable vectors covering, at
//! > minimum: canonical encoding of each class; identifier derivation; pairwise
//! > and inbox tag derivation across an epoch boundary; AAD construction;
//! > `mode_auth` and `mode_base` seal/open; each padding bucket boundary; and
//! > every rejection case in §11.
//! >
//! > Two independent implementations MUST agree on every vector before the
//! > status changes. **For a format that cannot be revised, vectors are the
//! > specification; the prose is commentary.**"
//!
//! # What this module is, and what it is not
//!
//! It emits `Documentation/vectors/rfc-1.txt` — a flat, line-oriented file
//! another implementation can read without a CBOR parser or a JSON library, in
//! any language. That matters because the audience is *the second
//! implementation*, which by definition does not share this one's code.
//!
//! The committed file is checked on every test run. If the implementation
//! drifts, the test fails; if the vectors are regenerated carelessly, the diff
//! is visible in review. Neither alone is sufficient and together they are the
//! protection.
//!
//! # The circularity, and where it is broken
//!
//! A vector file generated by the implementation it checks proves only
//! self-consistency. Two categories are therefore pinned to values computed
//! **outside** this codebase, in a separate HMAC implementation:
//!
//! - pairwise and inbox tags across an epoch boundary (§6.2)
//! - the HKDF-Expand construction underneath them
//!
//! Those are the derivations where an error is silent — RFC 0 §6 makes
//! delivery failure silent by design, so a wrong tag presents as "that peer
//! never receives anything" rather than as an error. The rest are
//! self-consistency checks against drift, which is what they can honestly be
//! until a second implementation exists.
//!
//! **RFC 1 cannot reach Final on this file alone.** §12 requires two
//! implementations to agree, and there is one.

use crate::compose::{aad_for, body_size_for, bucket_for, seal_to, Recipient, SUITE_V1};
use krab_core::object::{
    canonical_bytes, decode_envelope, Envelope, RoutingHeader, Tag, BUCKETS, ROUTING_HEADER_LEN,
};
use krab_core::tag::Epoch;
use krab_crypto::dh::SecretKey;
use krab_crypto::rng::NotRandom;
use krab_crypto::seal::{info_for, ENC_LEN};
use krab_store::index::{Reject, Store};

/// Where the committed file lives, relative to the workspace root.
pub const VECTOR_FILE: &str = "Documentation/vectors/rfc-1.txt";

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

fn sk(seed: u64) -> SecretKey {
    SecretKey::generate(&mut NotRandom::seeded(seed))
}

/// Produce every vector RFC 1 §12 enumerates.
pub fn generate() -> String {
    let mut out = String::new();
    out.push_str(
        "# RFC 1 §12 test vectors.\n\
         #\n\
         # Flat and line-oriented on purpose: the audience is a second\n\
         # implementation, which needs no CBOR parser to read this.\n\
         # Format: <name> <space> <hex or decimal>\n\
         #\n\
         # Generated by apps/krab-tui/src/vectors.rs and checked on every test\n\
         # run. RFC 1 §12 requires two independent implementations to agree\n\
         # before RFC 1 reaches Final; there is currently one.\n\n",
    );

    // ---- §8.1 padding bucket boundaries ----
    out.push_str("## bucket boundaries (§8.1)\n");
    for (i, size) in BUCKETS.iter().enumerate() {
        out.push_str(&format!("bucket.{i}.bytes {size}\n"));
        out.push_str(&format!(
            "bucket.for.{size} {}\n",
            bucket_for(*size as usize).unwrap()
        ));
        out.push_str(&format!(
            "bucket.for.{} {}\n",
            size + 1,
            bucket_for(*size as usize + 1)
                .map(|b| b.to_string())
                .unwrap_or("none".into())
        ));
    }
    out.push('\n');

    // ---- §4 canonical encoding and identifier derivation, per class ----
    out.push_str("## canonical encoding and identifiers (§4)\n");
    for class in 0u8..=1 {
        let h = RoutingHeader {
            version: 1,
            class,
            size_bucket: 0,
            flags: 0,
            expiry_min: 29_766_240,
            tag: Tag([0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88]),
        };
        out.push_str(&format!(
            "header.class{class}.encoded {}\n",
            hex(&h.write())
        ));
        let body = [0xABu8; 40];
        let obj = canonical_bytes(&h, &body).unwrap();
        out.push_str(&format!("object.class{class}.len {}\n", obj.len()));
        out.push_str(&format!(
            "object.class{class}.id {}\n",
            hex(&krab_crypto::object_id(&obj).0)
        ));
        // The identifier covers the padding: one flipped pad byte, one new id.
        let mut padded = obj.clone();
        *padded.last_mut().unwrap() = 1;
        out.push_str(&format!(
            "object.class{class}.id_with_dirty_padding {}\n",
            hex(&krab_crypto::object_id(&padded).0)
        ));
    }
    out.push('\n');

    // ---- §6.2 tag derivation across an epoch boundary ----
    //
    // A fixed PRK rather than a DH output, so the vector does not depend on
    // any implementation's clamping. These values are pinned independently in
    // `krab_crypto::kdf` against a separate HMAC implementation.
    // The construction itself, from a fixed PRK. **These are the anchored
    // ones**: a second implementation can check them with nothing but HMAC-
    // SHA256, without reproducing X25519's clamping, and the values here were
    // computed outside this codebase before being committed.
    out.push_str("## HKDF-Expand construction, fixed PRK (§6.2)\n");
    out.push_str("# prk = 42 repeated 32 times; independently computed.\n");
    out.push_str(&format!("kdf.prk {}\n", hex(&[0x42u8; 32])));
    for epoch in [20_670u32, 20_671, 20_672] {
        let e = Epoch(20_670);
        let _ = e;
        out.push_str(&format!(
            "kdf.pairwise.{epoch} {}\n",
            hex(&krab_crypto::kdf::expand_tag_for_vectors(
                &[0x42u8; 32],
                krab_core::tag::LABEL_TAG,
                Epoch(epoch)
            )
            .0)
        ));
        out.push_str(&format!(
            "kdf.inbox.{epoch} {}\n",
            hex(&krab_crypto::kdf::expand_tag_for_vectors(
                &[0x42u8; 32],
                krab_core::tag::LABEL_INBOX,
                Epoch(epoch)
            )
            .0)
        ));
    }
    out.push('\n');

    out.push_str("## tag derivation across an epoch boundary (§6.2)\n");
    let a = sk(1);
    let b = sk(2);
    let shared = krab_crypto::agree(&a, &b.public()).unwrap();
    out.push_str(&format!("kx.a.public {}\n", hex(&a.public().0)));
    out.push_str(&format!("kx.b.public {}\n", hex(&b.public().0)));
    for epoch in [20_670u32, 20_671, 20_672] {
        let e = Epoch(epoch);
        out.push_str(&format!(
            "tag.pairwise.{epoch} {}\n",
            hex(&krab_crypto::pairwise_tag(&shared, e).0)
        ));
        out.push_str(&format!(
            "tag.inbox.{epoch} {}\n",
            hex(&krab_crypto::inbox_tag(&b.public(), e).0)
        ));
    }
    out.push('\n');

    // ---- §6.1 AAD construction ----
    out.push_str("## AAD construction (§6.1)\n");
    let h = RoutingHeader {
        version: 1,
        class: 0,
        size_bucket: 1,
        flags: 0,
        expiry_min: 29_766_240,
        tag: Tag([9; 8]),
    };
    let enc = [0x5Au8; ENC_LEN];
    let env = Envelope {
        epoch: 20_671,
        tag_mode: 0,
        suite: SUITE_V1,
        enc: &enc,
        ciphertext: &[0xCC; 16],
    };
    out.push_str(&format!("aad.prefix {}\n", hex(&env.aad())));
    out.push_str(&format!("aad.full {}\n", hex(&aad_for(&h, &env))));
    out.push_str(&format!("info.class0 {}\n", hex(&info_for(0))));
    out.push_str(&format!("info.class1 {}\n", hex(&info_for(1))));
    out.push('\n');

    // ---- §6 seal/open, both modes ----
    //
    // HPKE is randomised, so a ciphertext is not a fixed vector. What is
    // pinned is the *shape*: sizes, and that a round trip through the wire
    // form recovers the plaintext.
    out.push_str("## seal and open (§6)\n");
    for (name, first_contact) in [("mode_auth", false), ("mode_base", true)] {
        let plaintext = b"vector plaintext";
        let epoch = Epoch(20_671);
        let tag = if first_contact {
            krab_crypto::inbox_tag(&b.public(), epoch)
        } else {
            krab_crypto::pairwise_tag(&shared, epoch)
        };
        let recipient = if first_contact {
            Recipient::FirstContact {
                correspondence: &b.public(),
                tag,
            }
        } else {
            Recipient::Known {
                correspondence: &b.public(),
                tag,
                chunk: None,
            }
        };
        let composed = seal_to(
            &a,
            &recipient,
            epoch,
            0,
            29_766_240,
            plaintext,
            &mut NotRandom::seeded(7),
        )
        .unwrap();
        let (env, _) = decode_envelope(&composed.bytes[ROUTING_HEADER_LEN..]).unwrap();
        out.push_str(&format!("{name}.object.len {}\n", composed.bytes.len()));
        out.push_str(&format!("{name}.bucket {}\n", composed.bucket));
        out.push_str(&format!("{name}.tag_mode {}\n", env.tag_mode));
        out.push_str(&format!("{name}.suite {}\n", env.suite));
        out.push_str(&format!("{name}.enc.len {}\n", env.enc.len()));
        out.push_str(&format!("{name}.ciphertext.len {}\n", env.ciphertext.len()));
        out.push_str(&format!("{name}.plaintext.len {}\n", plaintext.len()));
        out.push_str(&format!(
            "{name}.body_size_for {}\n",
            body_size_for(plaintext.len())
        ));
    }
    out.push('\n');

    // ---- §11 rejection cases ----
    out.push_str("## rejection cases (§11)\n");
    for (name, reject) in rejections() {
        out.push_str(&format!("reject.{name} {reject}\n"));
    }
    out
}

/// Every §11 rejection, exercised.
fn rejections() -> Vec<(&'static str, &'static str)> {
    let name_of = |r: Result<(), Reject>| -> &'static str {
        match r {
            Ok(()) => "accepted",
            Err(Reject::Expired) => "Expired",
            Err(Reject::TooFarFuture) => "TooFarFuture",
            Err(Reject::Duplicate) => "Duplicate",
            Err(Reject::Tombstoned) => "Tombstoned",
            Err(Reject::BelowWatermark) => "BelowWatermark",
            Err(Reject::Malformed) => "Malformed",
            Err(Reject::BadPadding) => "BadPadding",
            Err(Reject::IdMismatch) => "IdMismatch",
            Err(Reject::Unrecognised) => "Unrecognised",
            // No catch-all: a new `Reject` variant should fail to compile here
            // rather than silently render as "other" in a specification file.
        }
    };
    const NOW: u32 = 29_766_000;
    let object = |expiry: u32| {
        let h = RoutingHeader {
            version: 1,
            class: 0,
            size_bucket: 0,
            flags: 0,
            expiry_min: expiry,
            tag: Tag([7; 8]),
        };
        let b = canonical_bytes(&h, &[7u8; 40]).unwrap();
        (krab_crypto::object_id(&b), b)
    };

    let mut out = Vec::new();

    // I5 — the identifier must name the content.
    let mut s = Store::new();
    let (_, bytes) = object(NOW + 40_000);
    let (other, _) = object(NOW + 50_000);
    out.push((
        "id_mismatch",
        name_of(s.ingest(other, bytes.clone(), NOW, u32::MAX)),
    ));

    // I1 — length must equal the declared bucket.
    let mut short = bytes.clone();
    short.truncate(short.len() - 1);
    let id = krab_crypto::object_id(&short);
    out.push(("bad_length", name_of(s.ingest(id, short, NOW, u32::MAX))));

    // I2 — expiry in the past, and beyond MAX_TTL.
    let (id, b) = object(NOW - 1);
    out.push(("expired", name_of(s.ingest(id, b, NOW, u32::MAX))));
    let (id, b) = object(NOW + 100_000);
    out.push(("too_far_future", name_of(s.ingest(id, b, NOW, 1_000))));

    // I6 — duplicate.
    let (id, b) = object(NOW + 40_000);
    let _ = s.ingest(id, b.clone(), NOW, u32::MAX);
    out.push(("duplicate", name_of(s.ingest(id, b, NOW, u32::MAX))));

    // I3 — version and class must be recognised. A v2 object is well-formed
    // and unreadable here; storing it would mean relaying bytes whose meaning
    // this node cannot check.
    let mut junk = bytes.clone();
    junk[0] = 2; // version
    let id = krab_crypto::object_id(&junk);
    out.push(("bad_version", name_of(s.ingest(id, junk, NOW, u32::MAX))));

    let mut junk = bytes.clone();
    junk[1] = 0xFF; // class
    let id = krab_crypto::object_id(&junk);
    out.push(("bad_class", name_of(s.ingest(id, junk, NOW, u32::MAX))));

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn committed() -> Option<String> {
        // Tests run from the crate directory; the file lives at the workspace
        // root.
        std::fs::read_to_string(std::path::Path::new("../..").join(VECTOR_FILE)).ok()
    }

    /// **The drift check.** If the implementation changes, this fails; if the
    /// vectors are regenerated carelessly, the diff is visible in review.
    #[test]
    fn the_implementation_matches_the_committed_vectors() {
        let generated = generate();
        let Some(committed) = committed() else {
            panic!(
                "{VECTOR_FILE} is missing. Regenerate with:\n\n  \
                 cargo test -p krab-tui -- --ignored write_vectors\n"
            );
        };
        if generated != committed {
            let g: Vec<&str> = generated.lines().collect();
            let c: Vec<&str> = committed.lines().collect();
            let first = g
                .iter()
                .zip(c.iter())
                .position(|(a, b)| a != b)
                .map(|i| format!("line {}: {:?} vs committed {:?}", i + 1, g[i], c[i]))
                .unwrap_or_else(|| format!("length {} vs {}", g.len(), c.len()));
            panic!("vectors drifted — {first}");
        }
    }

    /// Regenerate. Ignored by default so it cannot silently paper over drift.
    #[test]
    #[ignore = "writes Documentation/vectors/rfc-1.txt"]
    fn write_vectors() {
        let path = std::path::Path::new("../..").join(VECTOR_FILE);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, generate()).unwrap();
    }

    /// §12's coverage list, checked item by item against the file rather than
    /// assumed. A vector file missing a category is worse than no file, since
    /// it implies coverage it does not have.
    #[test]
    fn every_category_rfc1_names_is_present() {
        let v = generate();
        for (category, marker) in [
            ("canonical encoding of each class", "header.class1.encoded"),
            ("identifier derivation", "object.class0.id "),
            (
                "pairwise tags across an epoch boundary",
                "tag.pairwise.20672",
            ),
            ("inbox tags across an epoch boundary", "tag.inbox.20672"),
            ("AAD construction", "aad.full"),
            ("mode_auth seal/open", "mode_auth.ciphertext.len"),
            ("mode_base seal/open", "mode_base.tag_mode"),
            ("each padding bucket boundary", "bucket.5.bytes"),
            ("§11 rejections", "reject.id_mismatch"),
        ] {
            assert!(
                v.contains(marker),
                "§12 requires {category}; {marker:?} is absent"
            );
        }
    }

    /// Every §11 rejection produces the expected refusal, not an acceptance.
    #[test]
    fn every_rejection_case_actually_rejects() {
        for (name, outcome) in rejections() {
            assert_ne!(outcome, "accepted", "§11 case {name} was accepted");
            assert_ne!(
                outcome, "other",
                "§11 case {name} produced an unnamed reject"
            );
        }
    }

    /// **Where the circularity is broken.** The fixed-PRK vectors were
    /// computed outside this codebase, with a separate HMAC implementation, and
    /// a second implementation can check them using nothing but HMAC-SHA256 —
    /// no X25519, no clamping, no shared assumptions.
    #[test]
    fn the_kdf_vectors_are_independently_anchored() {
        let v = generate();
        // Computed in Python before being committed here.
        for (line, expected) in [
            ("kdf.pairwise.20670", "9df7b6895987ed3c"),
            ("kdf.pairwise.20671", "2daceced91f7148c"),
            ("kdf.pairwise.20672", "77f7856b7dbebdea"),
            ("kdf.inbox.20670", "684f0e4dde844750"),
            ("kdf.inbox.20671", "249743bc3eadc595"),
            ("kdf.inbox.20672", "b4296a826dba95f8"),
        ] {
            assert!(
                v.contains(&format!("{line} {expected}")),
                "{line} does not match the independently computed {expected}"
            );
        }
    }

    /// The DH-derived tags cross an epoch boundary and stay distinct. These
    /// are *not* independently anchored — they depend on X25519 clamping — so
    /// they check drift rather than correctness.
    #[test]
    fn the_tag_vectors_cross_an_epoch_boundary() {
        let v = generate();
        assert!(v.contains("tag.pairwise.20670"));
        assert!(v.contains("tag.pairwise.20671"));
        assert!(v.contains("tag.pairwise.20672"));
        // Epoch boundary: three consecutive epochs, three distinct tags.
        let tags: Vec<&str> = v
            .lines()
            .filter(|l| l.starts_with("tag.pairwise."))
            .map(|l| l.split_whitespace().nth(1).unwrap())
            .collect();
        assert_eq!(tags.len(), 3);
        assert_ne!(tags[0], tags[1]);
        assert_ne!(tags[1], tags[2]);
    }
}
